/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: 'category',
      label: 'Getting Start',
      collapsed: false,
      items: ["intro"],
    },
    {
      type: 'category',
      label: 'Api',
      collapsed: false,
      items: ['api/Address', 'api/BlockTx', 'api/Contract', 'api/Crypto', 'api/Error',],
    },
    {
      type: 'category',
      label: 'Example',
      collapsed: false,
      items: [{
        type: 'category',
        label: 'App',
        collapsed: false,
        items: ["example/app/BiDirectionalPaymentChannel", "example/app/Create2", "example/app/CrowdFund", "example/app/DutchAuction", "example/app/EnglishAuction", "example/app/Erc20", "example/app/Erc721", "example/app/EtherWallet", "example/app/IterableMapping", "example/app/MerkleTree", "example/app/MinimalProxy", "example/app/MultiDelegatecall", "example/app/Muticall", "example/app/MutiSignWallet", "example/app/Proxy", "example/app/Slot", "example/app/UniDirectionalPaymentChannel", "example/app/UpgradeableProxy"]
      },
      {
        type: 'category',
        label: 'Defi',
        collapsed: false,
        items: ["example/defi/Chainlink", "example/defi/CPAMM", "example/defi/CSamm", "example/defi/Liquidity", "example/defi/Optimal", "example/defi/StakingRewards", "example/defi/Swap"]
      },
      {
        type: 'category',
        label: 'Practice',
        collapsed: false,
        items:["example/practice/PiggyBank"]
      },
        "example/AbiDecode", "example/AccountFactory",
        "example/Array", "example/BlockTimesatmp",
        "example/Call", "example/CallingContract", "example/Constants",
        "example/Constructor", "example/ContractSize", "example/Counter",
        "example/DataLocations", "example/Delegatecall", "example/DelegateCallAtack",
        "example/DenialOfSevice", "example/Echidna", "example/Enum", "example/Error",
        "example/EtherUnits", "example/Events", "example/ExternalContract",
        "example/Fallback", "example/FrontRunning", "example/Function",
        "example/FunctionModifier", "example/FunctionSelector", "example/Gas",
        "example/Hash", "example/Helloworld", "example/HoneyPot",
        "example/IfElse", "example/Immutable", "example/Import",
        "example/Inheritance", "example/Interface", "example/Keccak256",
        "example/Kill", "example/Library", "example/Loop", "example/Mapping",
        "example/NewContract", "example/NFTMultiMint", "example/Overflow",
        "example/Payable", "example/Primitives", "example/Randomness",
        "example/ReEntrancy", "example/SelfDestruct", "example/SendingEther", "example/Shadow",
        "example/Signature", "example/SignatureReplay", "example/SimpleStorage", "example/Structs",
        "example/Super", "example/TryCatch", "example/TxOrigin", "example/Variables",
        "example/Vault", "example/ViewAndPureFunctions", "example/Visibility"],
    },
    {
      type: 'category',
        label: 'Projects',
        collapsed: false,
      items:["projects/BabyToken","projects/Five","projects/MasterChef","projects/SushiBar"]
    },
    {
      type: 'category',
        label: 'Utils',
        collapsed: false,
      items:["utils/Verify"]
    }
    
  ],

  frontend: [
    {
      type: 'category',
      label: 'Getting Start',
      collapsed: false,
      items: ['frontend'],
    },
  ],
  // docs: [
  //   {
  //     type: "category",
  //     label: "Introduction",
  //     items: [
  //       "intro",
  //       "Api",
  //       "Example",
  //       "Projects",
  //       "Utils",
  //     ],
  //   },
  // ],
  // frontend:[

  // ]
  // docs: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Basic',
  //     collapsed: false,
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/deploy-your-site',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Extras',
  //     collapsed: false,
  //     items: [
  //       'tutorial-extras/manage-docs-versions',
  //       'tutorial-extras/translate-your-site',
  //     ],
  //   }
  // ],
  // solidity: [
  //   'introx',
  //   {
  //     type: 'category',
  //     label: 'Basic',
  //     collapsed: false,
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/deploy-your-site',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Extras',
  //     collapsed: false,
  //     items: [
  //       'tutorial-extras/manage-docs-versions',
  //       'tutorial-extras/translate-your-site',
  //     ],
  //   }
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
