/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: 'category',
      label: 'Getting Start',
      collapsed: false,
      items: ["intro"],
    },
    {
      type: 'category',
      label: 'Api',
      collapsed: false,
      items: ['solidity/api/Address', 'solidity/api/BlockTx', 'solidity/api/Contract', 'solidity/api/Crypto', 'solidity/api/Error',],
    },
    {
      type: 'category',
      label: 'Example',
      collapsed: false,
      items: [{
        type: 'category',
        label: 'App',
        collapsed: false,
        items: ["solidity/example/app/BiDirectionalPaymentChannel", "solidity/example/app/Create2", "solidity/example/app/CrowdFund", "solidity/example/app/DutchAuction", "solidity/example/app/EnglishAuction", "solidity/example/app/Erc20", "solidity/example/app/Erc721", "solidity/example/app/EtherWallet", "solidity/example/app/IterableMapping", "solidity/example/app/MerkleTree", "solidity/example/app/MinimalProxy", "solidity/example/app/MultiDelegatecall", "solidity/example/app/Muticall", "solidity/example/app/MutiSignWallet", "solidity/example/app/Proxy", "solidity/example/app/Slot", "solidity/example/app/UniDirectionalPaymentChannel", "solidity/example/app/UpgradeableProxy"]
      },
      {
        type: 'category',
        label: 'Defi',
        collapsed: false,
        items: ["solidity/example/defi/Chainlink", "solidity/example/defi/CPAMM", "solidity/example/defi/CSamm", "solidity/example/defi/Liquidity", "solidity/example/defi/Optimal", "solidity/example/defi/StakingRewards", "solidity/example/defi/Swap"]
      },
      {
        type: 'category',
        label: 'Practice',
        collapsed: false,
        items:["solidity/example/practice/PiggyBank"]
      },
        "solidity/example/AbiDecode", "solidity/example/AccountFactory",
        "solidity/example/Array", "solidity/example/BlockTimesatmp",
        "solidity/example/Call", "solidity/example/CallingContract", "solidity/example/Constants",
        "solidity/example/Constructor", "solidity/example/ContractSize", "solidity/example/Counter",
        "solidity/example/DataLocations", "solidity/example/Delegatecall", "solidity/example/DelegateCallAtack",
        "solidity/example/DenialOfSevice", "solidity/example/Echidna", "solidity/example/Enum", "solidity/example/Error",
        "solidity/example/EtherUnits", "solidity/example/Events", "solidity/example/ExternalContract",
        "solidity/example/Fallback", "solidity/example/FrontRunning", "solidity/example/Function",
        "solidity/example/FunctionModifier", "solidity/example/FunctionSelector", "solidity/example/Gas",
        "solidity/example/Hash", "solidity/example/Helloworld", "solidity/example/HoneyPot",
        "solidity/example/IfElse", "solidity/example/Immutable", "solidity/example/Import",
        "solidity/example/Inheritance", "solidity/example/Interface", "solidity/example/Keccak256",
        "solidity/example/Kill", "solidity/example/Library", "solidity/example/Loop", "solidity/example/Mapping",
        "solidity/example/NewContract", "solidity/example/NFTMultiMint", "solidity/example/Overflow",
        "solidity/example/Payable", "solidity/example/Primitives", "solidity/example/Randomness",
        "solidity/example/ReEntrancy", "solidity/example/SelfDestruct", "solidity/example/SendingEther", "solidity/example/Shadow",
        "solidity/example/Signature", "solidity/example/SignatureReplay", "solidity/example/SimpleStorage", "solidity/example/Structs",
        "solidity/example/Super", "solidity/example/TryCatch", "solidity/example/TxOrigin", "solidity/example/Variables",
        "solidity/example/Vault", "solidity/example/ViewAndPureFunctions", "solidity/example/Visibility"],
    },
    {
      type: 'category',
        label: 'Projects',
        collapsed: false,
      items:["solidity/projects/BabyToken","solidity/projects/Five","solidity/projects/MasterChef","solidity/projects/SushiBar"]
    },
    {
      type: 'category',
        label: 'Utils',
        collapsed: false,
      items:["solidity/utils/Verify"]
    }
    
  ],

  frontend: [
    {
      type: 'category',
      label: 'Getting Start',
      collapsed: false,
      items: ['frontend'],
    },
  ],
  evm: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: ['evm'],
    },
  ],
  dapp: [
    {
      type: 'category',
      label: 'Dapps',
      collapsed: false,
      items: ['dapp'],
    },
    {
      type: 'autogenerated',
      dirName: 'dapps', 
    },
  ],
  // docs: [
  //   {
  //     type: "category",
  //     label: "Introduction",
  //     items: [
  //       "intro",
  //       "Api",
  //       "Example",
  //       "Projects",
  //       "Utils",
  //     ],
  //   },
  // ],
  // frontend:[

  // ]
  // docs: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Basic',
  //     collapsed: false,
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/deploy-your-site',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Extras',
  //     collapsed: false,
  //     items: [
  //       'tutorial-extras/manage-docs-versions',
  //       'tutorial-extras/translate-your-site',
  //     ],
  //   }
  // ],
  // solidity: [
  //   'introx',
  //   {
  //     type: 'category',
  //     label: 'Basic',
  //     collapsed: false,
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/deploy-your-site',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Extras',
  //     collapsed: false,
  //     items: [
  //       'tutorial-extras/manage-docs-versions',
  //       'tutorial-extras/translate-your-site',
  //     ],
  //   }
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
